### ISSUE TITLE
Can you please, tell how did you find the pencil underline effect SVG,  I mean what tool you use for this 

### ISSUE THREAD

**Issue by brahma-XD** [codewithsadee/youdemi#1]
Can you please, tell how did you find the pencil underline effect SVG,  I mean what tool you use for this

**Comment by codewithsadee** [comment]
You can create using Adobe illustrator.

**Comment by brahma-XD** [comment]
Okay, Thanks Sadee for helping. Is there any online website or something from where I can get a pre made one ?

**Comment by codewithsadee** [comment]
[Freepik](https://www.freepik.com/vectors/)

**Comment by brahma-XD** [comment]
great, thank you so much sadee
